// <auto-generated />
namespace VITV.HRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class departmentbranchid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(departmentbranchid));
        
        string IMigrationMetadata.Id
        {
            get { return "201505121050296_department-branchid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
