// <auto-generated />
namespace VITV_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class repoterrole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(repoterrole));
        
        string IMigrationMetadata.Id
        {
            get { return "201412130242080_repoter-role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
