// <auto-generated />
namespace VITV_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class editrecruit3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editrecruit3));
        
        string IMigrationMetadata.Id
        {
            get { return "201407170412008_editrecruit3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
