// <auto-generated />
namespace VITV_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class uniquetitle_video : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uniquetitle_video));
        
        string IMigrationMetadata.Id
        {
            get { return "201412181030317_uniquetitle_video"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
