// <auto-generated />
namespace VITV_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class editrecruit5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editrecruit5));
        
        string IMigrationMetadata.Id
        {
            get { return "201407190413591_editrecruit5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
