// <auto-generated />
namespace VITV.Data.MigrationsGoogleAnalytcis
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class videoid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(videoid));
        
        string IMigrationMetadata.Id
        {
            get { return "201511270453053_videoid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
