// <auto-generated />
namespace VITV.Data.MigrationsStoreInfo
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class GoldPriceVietNam_Day : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GoldPriceVietNam_Day));
        
        string IMigrationMetadata.Id
        {
            get { return "201502020845509_GoldPriceVietNam_Day"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
