// <auto-generated />
namespace VITV.Data.MigrationsStoreInfo
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addStockVN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStockVN));
        
        string IMigrationMetadata.Id
        {
            get { return "201503070323159_addStockVN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
