// <auto-generated />
namespace VITV.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Uniquetile_videocatgroup2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Uniquetile_videocatgroup2));
        
        string IMigrationMetadata.Id
        {
            get { return "201503040330101_Uniquetile_videocatgroup2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
