// <auto-generated />
namespace VITV.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editvideoskipintro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editvideoskipintro));
        
        string IMigrationMetadata.Id
        {
            get { return "201507210423042_editvideo-skipintro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
