// <auto-generated />
namespace VITV.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editpageaccess1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editpageaccess1));
        
        string IMigrationMetadata.Id
        {
            get { return "201504220730219_editpageaccess1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
