// <auto-generated />
namespace VITV.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class name2videocategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(name2videocategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201509150348138_name2-videocategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
