//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VITVDataFeed.VITVService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VITVService.xmlVITVSoap")]
    public interface xmlVITVSoap {
        
        // CODEGEN: Generating message contract since element name getUS_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUS_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getUS_xmlResponse getUS_xml(VITVDataFeed.VITVService.getUS_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUS_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getUS_xmlResponse> getUS_xmlAsync(VITVDataFeed.VITVService.getUS_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name getVangTG_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVangTG_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getVangTG_xmlResponse getVangTG_xml(VITVDataFeed.VITVService.getVangTG_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVangTG_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getVangTG_xmlResponse> getVangTG_xmlAsync(VITVDataFeed.VITVService.getVangTG_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name getVangVietnam_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVangVietnam_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getVangVietnam_xmlResponse getVangVietnam_xml(VITVDataFeed.VITVService.getVangVietnam_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVangVietnam_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getVangVietnam_xmlResponse> getVangVietnam_xmlAsync(VITVDataFeed.VITVService.getVangVietnam_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name getTygiaUSD_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTygiaUSD_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getTygiaUSD_xmlResponse getTygiaUSD_xml(VITVDataFeed.VITVService.getTygiaUSD_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTygiaUSD_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getTygiaUSD_xmlResponse> getTygiaUSD_xmlAsync(VITVDataFeed.VITVService.getTygiaUSD_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name getTygiaVND_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTygiaVND_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getTygiaVND_xmlResponse getTygiaVND_xml(VITVDataFeed.VITVService.getTygiaVND_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTygiaVND_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getTygiaVND_xmlResponse> getTygiaVND_xmlAsync(VITVDataFeed.VITVService.getTygiaVND_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name getASIA_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getASIA_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getASIA_xmlResponse getASIA_xml(VITVDataFeed.VITVService.getASIA_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getASIA_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getASIA_xmlResponse> getASIA_xmlAsync(VITVDataFeed.VITVService.getASIA_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name getEUROPE_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEUROPE_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getEUROPE_xmlResponse getEUROPE_xml(VITVDataFeed.VITVService.getEUROPE_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEUROPE_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getEUROPE_xmlResponse> getEUROPE_xmlAsync(VITVDataFeed.VITVService.getEUROPE_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name getUSDIndex_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUSDIndex_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getUSDIndex_xmlResponse getUSDIndex_xml(VITVDataFeed.VITVService.getUSDIndex_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUSDIndex_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getUSDIndex_xmlResponse> getUSDIndex_xmlAsync(VITVDataFeed.VITVService.getUSDIndex_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name getDau_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDau_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getDau_xmlResponse getDau_xml(VITVDataFeed.VITVService.getDau_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDau_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getDau_xmlResponse> getDau_xmlAsync(VITVDataFeed.VITVService.getDau_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name getKimloai_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getKimloai_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getKimloai_xmlResponse getKimloai_xml(VITVDataFeed.VITVService.getKimloai_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getKimloai_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getKimloai_xmlResponse> getKimloai_xmlAsync(VITVDataFeed.VITVService.getKimloai_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name TygiaVND_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TygiaVND_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.TygiaVND_xmlResponse TygiaVND_xml(VITVDataFeed.VITVService.TygiaVND_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TygiaVND_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.TygiaVND_xmlResponse> TygiaVND_xmlAsync(VITVDataFeed.VITVService.TygiaVND_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name getStock_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStock_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getStock_xmlResponse getStock_xml(VITVDataFeed.VITVService.getStock_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStock_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getStock_xmlResponse> getStock_xmlAsync(VITVDataFeed.VITVService.getStock_xmlRequest request);
        
        // CODEGEN: Generating message contract since element name getHAHO_index_xmlResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHAHO_index_xml", ReplyAction="*")]
        VITVDataFeed.VITVService.getHAHO_index_xmlResponse getHAHO_index_xml(VITVDataFeed.VITVService.getHAHO_index_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHAHO_index_xml", ReplyAction="*")]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getHAHO_index_xmlResponse> getHAHO_index_xmlAsync(VITVDataFeed.VITVService.getHAHO_index_xmlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUS_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUS_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getUS_xmlRequestBody Body;
        
        public getUS_xmlRequest() {
        }
        
        public getUS_xmlRequest(VITVDataFeed.VITVService.getUS_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUS_xmlRequestBody {
        
        public getUS_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUS_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUS_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getUS_xmlResponseBody Body;
        
        public getUS_xmlResponse() {
        }
        
        public getUS_xmlResponse(VITVDataFeed.VITVService.getUS_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUS_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getUS_xmlResult;
        
        public getUS_xmlResponseBody() {
        }
        
        public getUS_xmlResponseBody(System.Xml.Linq.XElement getUS_xmlResult) {
            this.getUS_xmlResult = getUS_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVangTG_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVangTG_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getVangTG_xmlRequestBody Body;
        
        public getVangTG_xmlRequest() {
        }
        
        public getVangTG_xmlRequest(VITVDataFeed.VITVService.getVangTG_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getVangTG_xmlRequestBody {
        
        public getVangTG_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVangTG_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVangTG_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getVangTG_xmlResponseBody Body;
        
        public getVangTG_xmlResponse() {
        }
        
        public getVangTG_xmlResponse(VITVDataFeed.VITVService.getVangTG_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getVangTG_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getVangTG_xmlResult;
        
        public getVangTG_xmlResponseBody() {
        }
        
        public getVangTG_xmlResponseBody(System.Xml.Linq.XElement getVangTG_xmlResult) {
            this.getVangTG_xmlResult = getVangTG_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVangVietnam_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVangVietnam_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getVangVietnam_xmlRequestBody Body;
        
        public getVangVietnam_xmlRequest() {
        }
        
        public getVangVietnam_xmlRequest(VITVDataFeed.VITVService.getVangVietnam_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getVangVietnam_xmlRequestBody {
        
        public getVangVietnam_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVangVietnam_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVangVietnam_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getVangVietnam_xmlResponseBody Body;
        
        public getVangVietnam_xmlResponse() {
        }
        
        public getVangVietnam_xmlResponse(VITVDataFeed.VITVService.getVangVietnam_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getVangVietnam_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getVangVietnam_xmlResult;
        
        public getVangVietnam_xmlResponseBody() {
        }
        
        public getVangVietnam_xmlResponseBody(System.Xml.Linq.XElement getVangVietnam_xmlResult) {
            this.getVangVietnam_xmlResult = getVangVietnam_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTygiaUSD_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTygiaUSD_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getTygiaUSD_xmlRequestBody Body;
        
        public getTygiaUSD_xmlRequest() {
        }
        
        public getTygiaUSD_xmlRequest(VITVDataFeed.VITVService.getTygiaUSD_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getTygiaUSD_xmlRequestBody {
        
        public getTygiaUSD_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTygiaUSD_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTygiaUSD_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getTygiaUSD_xmlResponseBody Body;
        
        public getTygiaUSD_xmlResponse() {
        }
        
        public getTygiaUSD_xmlResponse(VITVDataFeed.VITVService.getTygiaUSD_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTygiaUSD_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getTygiaUSD_xmlResult;
        
        public getTygiaUSD_xmlResponseBody() {
        }
        
        public getTygiaUSD_xmlResponseBody(System.Xml.Linq.XElement getTygiaUSD_xmlResult) {
            this.getTygiaUSD_xmlResult = getTygiaUSD_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTygiaVND_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTygiaVND_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getTygiaVND_xmlRequestBody Body;
        
        public getTygiaVND_xmlRequest() {
        }
        
        public getTygiaVND_xmlRequest(VITVDataFeed.VITVService.getTygiaVND_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getTygiaVND_xmlRequestBody {
        
        public getTygiaVND_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTygiaVND_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTygiaVND_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getTygiaVND_xmlResponseBody Body;
        
        public getTygiaVND_xmlResponse() {
        }
        
        public getTygiaVND_xmlResponse(VITVDataFeed.VITVService.getTygiaVND_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTygiaVND_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getTygiaVND_xmlResult;
        
        public getTygiaVND_xmlResponseBody() {
        }
        
        public getTygiaVND_xmlResponseBody(System.Xml.Linq.XElement getTygiaVND_xmlResult) {
            this.getTygiaVND_xmlResult = getTygiaVND_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getASIA_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getASIA_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getASIA_xmlRequestBody Body;
        
        public getASIA_xmlRequest() {
        }
        
        public getASIA_xmlRequest(VITVDataFeed.VITVService.getASIA_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getASIA_xmlRequestBody {
        
        public getASIA_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getASIA_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getASIA_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getASIA_xmlResponseBody Body;
        
        public getASIA_xmlResponse() {
        }
        
        public getASIA_xmlResponse(VITVDataFeed.VITVService.getASIA_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getASIA_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getASIA_xmlResult;
        
        public getASIA_xmlResponseBody() {
        }
        
        public getASIA_xmlResponseBody(System.Xml.Linq.XElement getASIA_xmlResult) {
            this.getASIA_xmlResult = getASIA_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEUROPE_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEUROPE_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getEUROPE_xmlRequestBody Body;
        
        public getEUROPE_xmlRequest() {
        }
        
        public getEUROPE_xmlRequest(VITVDataFeed.VITVService.getEUROPE_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getEUROPE_xmlRequestBody {
        
        public getEUROPE_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEUROPE_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEUROPE_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getEUROPE_xmlResponseBody Body;
        
        public getEUROPE_xmlResponse() {
        }
        
        public getEUROPE_xmlResponse(VITVDataFeed.VITVService.getEUROPE_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEUROPE_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getEUROPE_xmlResult;
        
        public getEUROPE_xmlResponseBody() {
        }
        
        public getEUROPE_xmlResponseBody(System.Xml.Linq.XElement getEUROPE_xmlResult) {
            this.getEUROPE_xmlResult = getEUROPE_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUSDIndex_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUSDIndex_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getUSDIndex_xmlRequestBody Body;
        
        public getUSDIndex_xmlRequest() {
        }
        
        public getUSDIndex_xmlRequest(VITVDataFeed.VITVService.getUSDIndex_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUSDIndex_xmlRequestBody {
        
        public getUSDIndex_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUSDIndex_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUSDIndex_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getUSDIndex_xmlResponseBody Body;
        
        public getUSDIndex_xmlResponse() {
        }
        
        public getUSDIndex_xmlResponse(VITVDataFeed.VITVService.getUSDIndex_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUSDIndex_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getUSDIndex_xmlResult;
        
        public getUSDIndex_xmlResponseBody() {
        }
        
        public getUSDIndex_xmlResponseBody(System.Xml.Linq.XElement getUSDIndex_xmlResult) {
            this.getUSDIndex_xmlResult = getUSDIndex_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDau_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDau_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getDau_xmlRequestBody Body;
        
        public getDau_xmlRequest() {
        }
        
        public getDau_xmlRequest(VITVDataFeed.VITVService.getDau_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getDau_xmlRequestBody {
        
        public getDau_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDau_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDau_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getDau_xmlResponseBody Body;
        
        public getDau_xmlResponse() {
        }
        
        public getDau_xmlResponse(VITVDataFeed.VITVService.getDau_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDau_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getDau_xmlResult;
        
        public getDau_xmlResponseBody() {
        }
        
        public getDau_xmlResponseBody(System.Xml.Linq.XElement getDau_xmlResult) {
            this.getDau_xmlResult = getDau_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKimloai_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getKimloai_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getKimloai_xmlRequestBody Body;
        
        public getKimloai_xmlRequest() {
        }
        
        public getKimloai_xmlRequest(VITVDataFeed.VITVService.getKimloai_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getKimloai_xmlRequestBody {
        
        public getKimloai_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKimloai_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getKimloai_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getKimloai_xmlResponseBody Body;
        
        public getKimloai_xmlResponse() {
        }
        
        public getKimloai_xmlResponse(VITVDataFeed.VITVService.getKimloai_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getKimloai_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getKimloai_xmlResult;
        
        public getKimloai_xmlResponseBody() {
        }
        
        public getKimloai_xmlResponseBody(System.Xml.Linq.XElement getKimloai_xmlResult) {
            this.getKimloai_xmlResult = getKimloai_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TygiaVND_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TygiaVND_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.TygiaVND_xmlRequestBody Body;
        
        public TygiaVND_xmlRequest() {
        }
        
        public TygiaVND_xmlRequest(VITVDataFeed.VITVService.TygiaVND_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TygiaVND_xmlRequestBody {
        
        public TygiaVND_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TygiaVND_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TygiaVND_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.TygiaVND_xmlResponseBody Body;
        
        public TygiaVND_xmlResponse() {
        }
        
        public TygiaVND_xmlResponse(VITVDataFeed.VITVService.TygiaVND_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TygiaVND_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement TygiaVND_xmlResult;
        
        public TygiaVND_xmlResponseBody() {
        }
        
        public TygiaVND_xmlResponseBody(System.Xml.Linq.XElement TygiaVND_xmlResult) {
            this.TygiaVND_xmlResult = TygiaVND_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStock_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStock_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getStock_xmlRequestBody Body;
        
        public getStock_xmlRequest() {
        }
        
        public getStock_xmlRequest(VITVDataFeed.VITVService.getStock_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getStock_xmlRequestBody {
        
        public getStock_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStock_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStock_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getStock_xmlResponseBody Body;
        
        public getStock_xmlResponse() {
        }
        
        public getStock_xmlResponse(VITVDataFeed.VITVService.getStock_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStock_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getStock_xmlResult;
        
        public getStock_xmlResponseBody() {
        }
        
        public getStock_xmlResponseBody(System.Xml.Linq.XElement getStock_xmlResult) {
            this.getStock_xmlResult = getStock_xmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHAHO_index_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHAHO_index_xml", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getHAHO_index_xmlRequestBody Body;
        
        public getHAHO_index_xmlRequest() {
        }
        
        public getHAHO_index_xmlRequest(VITVDataFeed.VITVService.getHAHO_index_xmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getHAHO_index_xmlRequestBody {
        
        public getHAHO_index_xmlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHAHO_index_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHAHO_index_xmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public VITVDataFeed.VITVService.getHAHO_index_xmlResponseBody Body;
        
        public getHAHO_index_xmlResponse() {
        }
        
        public getHAHO_index_xmlResponse(VITVDataFeed.VITVService.getHAHO_index_xmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHAHO_index_xmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getHAHO_index_xmlResult;
        
        public getHAHO_index_xmlResponseBody() {
        }
        
        public getHAHO_index_xmlResponseBody(System.Xml.Linq.XElement getHAHO_index_xmlResult) {
            this.getHAHO_index_xmlResult = getHAHO_index_xmlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface xmlVITVSoapChannel : VITVDataFeed.VITVService.xmlVITVSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class xmlVITVSoapClient : System.ServiceModel.ClientBase<VITVDataFeed.VITVService.xmlVITVSoap>, VITVDataFeed.VITVService.xmlVITVSoap {
        
        public xmlVITVSoapClient() {
        }
        
        public xmlVITVSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public xmlVITVSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public xmlVITVSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public xmlVITVSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getUS_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getUS_xml(VITVDataFeed.VITVService.getUS_xmlRequest request) {
            return base.Channel.getUS_xml(request);
        }
        
        public System.Xml.Linq.XElement getUS_xml() {
            VITVDataFeed.VITVService.getUS_xmlRequest inValue = new VITVDataFeed.VITVService.getUS_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getUS_xmlRequestBody();
            VITVDataFeed.VITVService.getUS_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getUS_xml(inValue);
            return retVal.Body.getUS_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getUS_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getUS_xmlAsync(VITVDataFeed.VITVService.getUS_xmlRequest request) {
            return base.Channel.getUS_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getUS_xmlResponse> getUS_xmlAsync() {
            VITVDataFeed.VITVService.getUS_xmlRequest inValue = new VITVDataFeed.VITVService.getUS_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getUS_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getUS_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getVangTG_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getVangTG_xml(VITVDataFeed.VITVService.getVangTG_xmlRequest request) {
            return base.Channel.getVangTG_xml(request);
        }
        
        public System.Xml.Linq.XElement getVangTG_xml() {
            VITVDataFeed.VITVService.getVangTG_xmlRequest inValue = new VITVDataFeed.VITVService.getVangTG_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getVangTG_xmlRequestBody();
            VITVDataFeed.VITVService.getVangTG_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getVangTG_xml(inValue);
            return retVal.Body.getVangTG_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getVangTG_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getVangTG_xmlAsync(VITVDataFeed.VITVService.getVangTG_xmlRequest request) {
            return base.Channel.getVangTG_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getVangTG_xmlResponse> getVangTG_xmlAsync() {
            VITVDataFeed.VITVService.getVangTG_xmlRequest inValue = new VITVDataFeed.VITVService.getVangTG_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getVangTG_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getVangTG_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getVangVietnam_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getVangVietnam_xml(VITVDataFeed.VITVService.getVangVietnam_xmlRequest request) {
            return base.Channel.getVangVietnam_xml(request);
        }
        
        public System.Xml.Linq.XElement getVangVietnam_xml() {
            VITVDataFeed.VITVService.getVangVietnam_xmlRequest inValue = new VITVDataFeed.VITVService.getVangVietnam_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getVangVietnam_xmlRequestBody();
            VITVDataFeed.VITVService.getVangVietnam_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getVangVietnam_xml(inValue);
            return retVal.Body.getVangVietnam_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getVangVietnam_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getVangVietnam_xmlAsync(VITVDataFeed.VITVService.getVangVietnam_xmlRequest request) {
            return base.Channel.getVangVietnam_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getVangVietnam_xmlResponse> getVangVietnam_xmlAsync() {
            VITVDataFeed.VITVService.getVangVietnam_xmlRequest inValue = new VITVDataFeed.VITVService.getVangVietnam_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getVangVietnam_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getVangVietnam_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getTygiaUSD_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getTygiaUSD_xml(VITVDataFeed.VITVService.getTygiaUSD_xmlRequest request) {
            return base.Channel.getTygiaUSD_xml(request);
        }
        
        public System.Xml.Linq.XElement getTygiaUSD_xml() {
            VITVDataFeed.VITVService.getTygiaUSD_xmlRequest inValue = new VITVDataFeed.VITVService.getTygiaUSD_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getTygiaUSD_xmlRequestBody();
            VITVDataFeed.VITVService.getTygiaUSD_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getTygiaUSD_xml(inValue);
            return retVal.Body.getTygiaUSD_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getTygiaUSD_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getTygiaUSD_xmlAsync(VITVDataFeed.VITVService.getTygiaUSD_xmlRequest request) {
            return base.Channel.getTygiaUSD_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getTygiaUSD_xmlResponse> getTygiaUSD_xmlAsync() {
            VITVDataFeed.VITVService.getTygiaUSD_xmlRequest inValue = new VITVDataFeed.VITVService.getTygiaUSD_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getTygiaUSD_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getTygiaUSD_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getTygiaVND_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getTygiaVND_xml(VITVDataFeed.VITVService.getTygiaVND_xmlRequest request) {
            return base.Channel.getTygiaVND_xml(request);
        }
        
        public System.Xml.Linq.XElement getTygiaVND_xml() {
            VITVDataFeed.VITVService.getTygiaVND_xmlRequest inValue = new VITVDataFeed.VITVService.getTygiaVND_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getTygiaVND_xmlRequestBody();
            VITVDataFeed.VITVService.getTygiaVND_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getTygiaVND_xml(inValue);
            return retVal.Body.getTygiaVND_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getTygiaVND_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getTygiaVND_xmlAsync(VITVDataFeed.VITVService.getTygiaVND_xmlRequest request) {
            return base.Channel.getTygiaVND_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getTygiaVND_xmlResponse> getTygiaVND_xmlAsync() {
            VITVDataFeed.VITVService.getTygiaVND_xmlRequest inValue = new VITVDataFeed.VITVService.getTygiaVND_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getTygiaVND_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getTygiaVND_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getASIA_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getASIA_xml(VITVDataFeed.VITVService.getASIA_xmlRequest request) {
            return base.Channel.getASIA_xml(request);
        }
        
        public System.Xml.Linq.XElement getASIA_xml() {
            VITVDataFeed.VITVService.getASIA_xmlRequest inValue = new VITVDataFeed.VITVService.getASIA_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getASIA_xmlRequestBody();
            VITVDataFeed.VITVService.getASIA_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getASIA_xml(inValue);
            return retVal.Body.getASIA_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getASIA_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getASIA_xmlAsync(VITVDataFeed.VITVService.getASIA_xmlRequest request) {
            return base.Channel.getASIA_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getASIA_xmlResponse> getASIA_xmlAsync() {
            VITVDataFeed.VITVService.getASIA_xmlRequest inValue = new VITVDataFeed.VITVService.getASIA_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getASIA_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getASIA_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getEUROPE_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getEUROPE_xml(VITVDataFeed.VITVService.getEUROPE_xmlRequest request) {
            return base.Channel.getEUROPE_xml(request);
        }
        
        public System.Xml.Linq.XElement getEUROPE_xml() {
            VITVDataFeed.VITVService.getEUROPE_xmlRequest inValue = new VITVDataFeed.VITVService.getEUROPE_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getEUROPE_xmlRequestBody();
            VITVDataFeed.VITVService.getEUROPE_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getEUROPE_xml(inValue);
            return retVal.Body.getEUROPE_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getEUROPE_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getEUROPE_xmlAsync(VITVDataFeed.VITVService.getEUROPE_xmlRequest request) {
            return base.Channel.getEUROPE_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getEUROPE_xmlResponse> getEUROPE_xmlAsync() {
            VITVDataFeed.VITVService.getEUROPE_xmlRequest inValue = new VITVDataFeed.VITVService.getEUROPE_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getEUROPE_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getEUROPE_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getUSDIndex_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getUSDIndex_xml(VITVDataFeed.VITVService.getUSDIndex_xmlRequest request) {
            return base.Channel.getUSDIndex_xml(request);
        }
        
        public System.Xml.Linq.XElement getUSDIndex_xml() {
            VITVDataFeed.VITVService.getUSDIndex_xmlRequest inValue = new VITVDataFeed.VITVService.getUSDIndex_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getUSDIndex_xmlRequestBody();
            VITVDataFeed.VITVService.getUSDIndex_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getUSDIndex_xml(inValue);
            return retVal.Body.getUSDIndex_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getUSDIndex_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getUSDIndex_xmlAsync(VITVDataFeed.VITVService.getUSDIndex_xmlRequest request) {
            return base.Channel.getUSDIndex_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getUSDIndex_xmlResponse> getUSDIndex_xmlAsync() {
            VITVDataFeed.VITVService.getUSDIndex_xmlRequest inValue = new VITVDataFeed.VITVService.getUSDIndex_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getUSDIndex_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getUSDIndex_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getDau_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getDau_xml(VITVDataFeed.VITVService.getDau_xmlRequest request) {
            return base.Channel.getDau_xml(request);
        }
        
        public System.Xml.Linq.XElement getDau_xml() {
            VITVDataFeed.VITVService.getDau_xmlRequest inValue = new VITVDataFeed.VITVService.getDau_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getDau_xmlRequestBody();
            VITVDataFeed.VITVService.getDau_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getDau_xml(inValue);
            return retVal.Body.getDau_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getDau_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getDau_xmlAsync(VITVDataFeed.VITVService.getDau_xmlRequest request) {
            return base.Channel.getDau_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getDau_xmlResponse> getDau_xmlAsync() {
            VITVDataFeed.VITVService.getDau_xmlRequest inValue = new VITVDataFeed.VITVService.getDau_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getDau_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getDau_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getKimloai_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getKimloai_xml(VITVDataFeed.VITVService.getKimloai_xmlRequest request) {
            return base.Channel.getKimloai_xml(request);
        }
        
        public System.Xml.Linq.XElement getKimloai_xml() {
            VITVDataFeed.VITVService.getKimloai_xmlRequest inValue = new VITVDataFeed.VITVService.getKimloai_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getKimloai_xmlRequestBody();
            VITVDataFeed.VITVService.getKimloai_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getKimloai_xml(inValue);
            return retVal.Body.getKimloai_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getKimloai_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getKimloai_xmlAsync(VITVDataFeed.VITVService.getKimloai_xmlRequest request) {
            return base.Channel.getKimloai_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getKimloai_xmlResponse> getKimloai_xmlAsync() {
            VITVDataFeed.VITVService.getKimloai_xmlRequest inValue = new VITVDataFeed.VITVService.getKimloai_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getKimloai_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getKimloai_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.TygiaVND_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.TygiaVND_xml(VITVDataFeed.VITVService.TygiaVND_xmlRequest request) {
            return base.Channel.TygiaVND_xml(request);
        }
        
        public System.Xml.Linq.XElement TygiaVND_xml() {
            VITVDataFeed.VITVService.TygiaVND_xmlRequest inValue = new VITVDataFeed.VITVService.TygiaVND_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.TygiaVND_xmlRequestBody();
            VITVDataFeed.VITVService.TygiaVND_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).TygiaVND_xml(inValue);
            return retVal.Body.TygiaVND_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.TygiaVND_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.TygiaVND_xmlAsync(VITVDataFeed.VITVService.TygiaVND_xmlRequest request) {
            return base.Channel.TygiaVND_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.TygiaVND_xmlResponse> TygiaVND_xmlAsync() {
            VITVDataFeed.VITVService.TygiaVND_xmlRequest inValue = new VITVDataFeed.VITVService.TygiaVND_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.TygiaVND_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).TygiaVND_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getStock_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getStock_xml(VITVDataFeed.VITVService.getStock_xmlRequest request) {
            return base.Channel.getStock_xml(request);
        }
        
        public System.Xml.Linq.XElement getStock_xml() {
            VITVDataFeed.VITVService.getStock_xmlRequest inValue = new VITVDataFeed.VITVService.getStock_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getStock_xmlRequestBody();
            VITVDataFeed.VITVService.getStock_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getStock_xml(inValue);
            return retVal.Body.getStock_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getStock_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getStock_xmlAsync(VITVDataFeed.VITVService.getStock_xmlRequest request) {
            return base.Channel.getStock_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getStock_xmlResponse> getStock_xmlAsync() {
            VITVDataFeed.VITVService.getStock_xmlRequest inValue = new VITVDataFeed.VITVService.getStock_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getStock_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getStock_xmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VITVDataFeed.VITVService.getHAHO_index_xmlResponse VITVDataFeed.VITVService.xmlVITVSoap.getHAHO_index_xml(VITVDataFeed.VITVService.getHAHO_index_xmlRequest request) {
            return base.Channel.getHAHO_index_xml(request);
        }
        
        public System.Xml.Linq.XElement getHAHO_index_xml() {
            VITVDataFeed.VITVService.getHAHO_index_xmlRequest inValue = new VITVDataFeed.VITVService.getHAHO_index_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getHAHO_index_xmlRequestBody();
            VITVDataFeed.VITVService.getHAHO_index_xmlResponse retVal = ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getHAHO_index_xml(inValue);
            return retVal.Body.getHAHO_index_xmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VITVDataFeed.VITVService.getHAHO_index_xmlResponse> VITVDataFeed.VITVService.xmlVITVSoap.getHAHO_index_xmlAsync(VITVDataFeed.VITVService.getHAHO_index_xmlRequest request) {
            return base.Channel.getHAHO_index_xmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<VITVDataFeed.VITVService.getHAHO_index_xmlResponse> getHAHO_index_xmlAsync() {
            VITVDataFeed.VITVService.getHAHO_index_xmlRequest inValue = new VITVDataFeed.VITVService.getHAHO_index_xmlRequest();
            inValue.Body = new VITVDataFeed.VITVService.getHAHO_index_xmlRequestBody();
            return ((VITVDataFeed.VITVService.xmlVITVSoap)(this)).getHAHO_index_xmlAsync(inValue);
        }
    }
}
