//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VITV_Web.SSIStockService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ssi.com.vn/", ConfigurationName="SSIStockService.AjaxWebServiceSoap")]
    public interface AjaxWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetStatusBasePrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetStatusBasePrice(int tradingFloor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetStatusBasePrice", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetStatusBasePriceAsync(int tradingFloor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHoseIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHoseIndex();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHoseIndex", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHoseIndexAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetDataHoseStockList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDataHoseStockList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetDataHoseStockList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDataHoseStockListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHoseStockQuoteInit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHoseStockQuoteInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHoseStockQuoteInit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHoseStockQuoteInitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHoseStockQuote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHoseStockQuote(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHoseStockQuote", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHoseStockQuoteAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHoseIndexChart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHoseIndexChart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHoseIndexChart", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHoseIndexChartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHosePTInit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHosePTInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHosePTInit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHosePTInitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHosePTMatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHosePTMatch(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHosePTMatch", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHosePTMatchAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHosePTBid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHosePTBid(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHosePTBid", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHosePTBidAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHosePTOffer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHosePTOffer(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHosePTOffer", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHosePTOfferAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHose30Index", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHose30Index();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHose30Index", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHose30IndexAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetDataHose30StockList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDataHose30StockList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetDataHose30StockList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDataHose30StockListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHose30StockQuoteInit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHose30StockQuoteInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHose30StockQuoteInit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHose30StockQuoteInitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHose30StockQuote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHose30StockQuote(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHose30StockQuote", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHose30StockQuoteAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnxIndex();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxIndex", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnxIndexAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetDataHnxStockList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDataHnxStockList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetDataHnxStockList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDataHnxStockListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxStockQuoteInit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnxStockQuoteInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxStockQuoteInit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnxStockQuoteInitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxStockQuote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnxStockQuote(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxStockQuote", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnxStockQuoteAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxTop3Price", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnxTop3Price(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxTop3Price", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnxTop3PriceAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxIndexChart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnxIndexChart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxIndexChart", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnxIndexChartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxPTInit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnxPTInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxPTInit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnxPTInitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxPTMatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnxPTMatch(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxPTMatch", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnxPTMatchAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxPTBid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnxPTBid(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxPTBid", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnxPTBidAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxPTOffer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnxPTOffer(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnxPTOffer", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnxPTOfferAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnx30Index", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnx30Index();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnx30Index", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnx30IndexAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnx30StockList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnx30StockList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnx30StockList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnx30StockListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnx30StockQuoteInit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnx30StockQuoteInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnx30StockQuoteInit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnx30StockQuoteInitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnx30StockQuote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnx30StockQuote(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnx30StockQuote", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnx30StockQuoteAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnx30Top3Price", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHnx30Top3Price(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetHnx30Top3Price", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHnx30Top3PriceAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetMarketAllIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMarketAllIndex(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetMarketAllIndex", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMarketAllIndexAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUpcomIndex();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomIndex", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUpcomIndexAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomStockList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUpcomStockList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomStockList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUpcomStockListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomStockQuoteInit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUpcomStockQuoteInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomStockQuoteInit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUpcomStockQuoteInitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomStockQuote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUpcomStockQuote(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomStockQuote", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUpcomStockQuoteAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomTop3Price", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUpcomTop3Price(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomTop3Price", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUpcomTop3PriceAsync(long VersionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomIndexChart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUpcomIndexChart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomIndexChart", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUpcomIndexChartAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AjaxWebServiceSoapChannel : VITV_Web.SSIStockService.AjaxWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AjaxWebServiceSoapClient : System.ServiceModel.ClientBase<VITV_Web.SSIStockService.AjaxWebServiceSoap>, VITV_Web.SSIStockService.AjaxWebServiceSoap {
        
        public AjaxWebServiceSoapClient() {
        }
        
        public AjaxWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AjaxWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AjaxWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AjaxWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStatusBasePrice(int tradingFloor) {
            return base.Channel.GetStatusBasePrice(tradingFloor);
        }
        
        public System.Threading.Tasks.Task<string> GetStatusBasePriceAsync(int tradingFloor) {
            return base.Channel.GetStatusBasePriceAsync(tradingFloor);
        }
        
        public string GetHoseIndex() {
            return base.Channel.GetHoseIndex();
        }
        
        public System.Threading.Tasks.Task<string> GetHoseIndexAsync() {
            return base.Channel.GetHoseIndexAsync();
        }
        
        public string GetDataHoseStockList() {
            return base.Channel.GetDataHoseStockList();
        }
        
        public System.Threading.Tasks.Task<string> GetDataHoseStockListAsync() {
            return base.Channel.GetDataHoseStockListAsync();
        }
        
        public string GetHoseStockQuoteInit() {
            return base.Channel.GetHoseStockQuoteInit();
        }
        
        public System.Threading.Tasks.Task<string> GetHoseStockQuoteInitAsync() {
            return base.Channel.GetHoseStockQuoteInitAsync();
        }
        
        public string GetHoseStockQuote(long VersionId) {
            return base.Channel.GetHoseStockQuote(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHoseStockQuoteAsync(long VersionId) {
            return base.Channel.GetHoseStockQuoteAsync(VersionId);
        }
        
        public string GetHoseIndexChart() {
            return base.Channel.GetHoseIndexChart();
        }
        
        public System.Threading.Tasks.Task<string> GetHoseIndexChartAsync() {
            return base.Channel.GetHoseIndexChartAsync();
        }
        
        public string GetHosePTInit() {
            return base.Channel.GetHosePTInit();
        }
        
        public System.Threading.Tasks.Task<string> GetHosePTInitAsync() {
            return base.Channel.GetHosePTInitAsync();
        }
        
        public string GetHosePTMatch(long VersionId) {
            return base.Channel.GetHosePTMatch(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHosePTMatchAsync(long VersionId) {
            return base.Channel.GetHosePTMatchAsync(VersionId);
        }
        
        public string GetHosePTBid(long VersionId) {
            return base.Channel.GetHosePTBid(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHosePTBidAsync(long VersionId) {
            return base.Channel.GetHosePTBidAsync(VersionId);
        }
        
        public string GetHosePTOffer(long VersionId) {
            return base.Channel.GetHosePTOffer(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHosePTOfferAsync(long VersionId) {
            return base.Channel.GetHosePTOfferAsync(VersionId);
        }
        
        public string GetHose30Index() {
            return base.Channel.GetHose30Index();
        }
        
        public System.Threading.Tasks.Task<string> GetHose30IndexAsync() {
            return base.Channel.GetHose30IndexAsync();
        }
        
        public string GetDataHose30StockList() {
            return base.Channel.GetDataHose30StockList();
        }
        
        public System.Threading.Tasks.Task<string> GetDataHose30StockListAsync() {
            return base.Channel.GetDataHose30StockListAsync();
        }
        
        public string GetHose30StockQuoteInit() {
            return base.Channel.GetHose30StockQuoteInit();
        }
        
        public System.Threading.Tasks.Task<string> GetHose30StockQuoteInitAsync() {
            return base.Channel.GetHose30StockQuoteInitAsync();
        }
        
        public string GetHose30StockQuote(long VersionId) {
            return base.Channel.GetHose30StockQuote(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHose30StockQuoteAsync(long VersionId) {
            return base.Channel.GetHose30StockQuoteAsync(VersionId);
        }
        
        public string GetHnxIndex() {
            return base.Channel.GetHnxIndex();
        }
        
        public System.Threading.Tasks.Task<string> GetHnxIndexAsync() {
            return base.Channel.GetHnxIndexAsync();
        }
        
        public string GetDataHnxStockList() {
            return base.Channel.GetDataHnxStockList();
        }
        
        public System.Threading.Tasks.Task<string> GetDataHnxStockListAsync() {
            return base.Channel.GetDataHnxStockListAsync();
        }
        
        public string GetHnxStockQuoteInit() {
            return base.Channel.GetHnxStockQuoteInit();
        }
        
        public System.Threading.Tasks.Task<string> GetHnxStockQuoteInitAsync() {
            return base.Channel.GetHnxStockQuoteInitAsync();
        }
        
        public string GetHnxStockQuote(long VersionId) {
            return base.Channel.GetHnxStockQuote(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHnxStockQuoteAsync(long VersionId) {
            return base.Channel.GetHnxStockQuoteAsync(VersionId);
        }
        
        public string GetHnxTop3Price(long VersionId) {
            return base.Channel.GetHnxTop3Price(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHnxTop3PriceAsync(long VersionId) {
            return base.Channel.GetHnxTop3PriceAsync(VersionId);
        }
        
        public string GetHnxIndexChart() {
            return base.Channel.GetHnxIndexChart();
        }
        
        public System.Threading.Tasks.Task<string> GetHnxIndexChartAsync() {
            return base.Channel.GetHnxIndexChartAsync();
        }
        
        public string GetHnxPTInit() {
            return base.Channel.GetHnxPTInit();
        }
        
        public System.Threading.Tasks.Task<string> GetHnxPTInitAsync() {
            return base.Channel.GetHnxPTInitAsync();
        }
        
        public string GetHnxPTMatch(long VersionId) {
            return base.Channel.GetHnxPTMatch(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHnxPTMatchAsync(long VersionId) {
            return base.Channel.GetHnxPTMatchAsync(VersionId);
        }
        
        public string GetHnxPTBid(long VersionId) {
            return base.Channel.GetHnxPTBid(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHnxPTBidAsync(long VersionId) {
            return base.Channel.GetHnxPTBidAsync(VersionId);
        }
        
        public string GetHnxPTOffer(long VersionId) {
            return base.Channel.GetHnxPTOffer(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHnxPTOfferAsync(long VersionId) {
            return base.Channel.GetHnxPTOfferAsync(VersionId);
        }
        
        public string GetHnx30Index() {
            return base.Channel.GetHnx30Index();
        }
        
        public System.Threading.Tasks.Task<string> GetHnx30IndexAsync() {
            return base.Channel.GetHnx30IndexAsync();
        }
        
        public string GetHnx30StockList() {
            return base.Channel.GetHnx30StockList();
        }
        
        public System.Threading.Tasks.Task<string> GetHnx30StockListAsync() {
            return base.Channel.GetHnx30StockListAsync();
        }
        
        public string GetHnx30StockQuoteInit() {
            return base.Channel.GetHnx30StockQuoteInit();
        }
        
        public System.Threading.Tasks.Task<string> GetHnx30StockQuoteInitAsync() {
            return base.Channel.GetHnx30StockQuoteInitAsync();
        }
        
        public string GetHnx30StockQuote(long VersionId) {
            return base.Channel.GetHnx30StockQuote(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHnx30StockQuoteAsync(long VersionId) {
            return base.Channel.GetHnx30StockQuoteAsync(VersionId);
        }
        
        public string GetHnx30Top3Price(long VersionId) {
            return base.Channel.GetHnx30Top3Price(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetHnx30Top3PriceAsync(long VersionId) {
            return base.Channel.GetHnx30Top3PriceAsync(VersionId);
        }
        
        public string GetMarketAllIndex(long VersionId) {
            return base.Channel.GetMarketAllIndex(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetMarketAllIndexAsync(long VersionId) {
            return base.Channel.GetMarketAllIndexAsync(VersionId);
        }
        
        public string GetUpcomIndex() {
            return base.Channel.GetUpcomIndex();
        }
        
        public System.Threading.Tasks.Task<string> GetUpcomIndexAsync() {
            return base.Channel.GetUpcomIndexAsync();
        }
        
        public string GetUpcomStockList() {
            return base.Channel.GetUpcomStockList();
        }
        
        public System.Threading.Tasks.Task<string> GetUpcomStockListAsync() {
            return base.Channel.GetUpcomStockListAsync();
        }
        
        public string GetUpcomStockQuoteInit() {
            return base.Channel.GetUpcomStockQuoteInit();
        }
        
        public System.Threading.Tasks.Task<string> GetUpcomStockQuoteInitAsync() {
            return base.Channel.GetUpcomStockQuoteInitAsync();
        }
        
        public string GetUpcomStockQuote(long VersionId) {
            return base.Channel.GetUpcomStockQuote(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetUpcomStockQuoteAsync(long VersionId) {
            return base.Channel.GetUpcomStockQuoteAsync(VersionId);
        }
        
        public string GetUpcomTop3Price(long VersionId) {
            return base.Channel.GetUpcomTop3Price(VersionId);
        }
        
        public System.Threading.Tasks.Task<string> GetUpcomTop3PriceAsync(long VersionId) {
            return base.Channel.GetUpcomTop3PriceAsync(VersionId);
        }
        
        public string GetUpcomIndexChart() {
            return base.Channel.GetUpcomIndexChart();
        }
        
        public System.Threading.Tasks.Task<string> GetUpcomIndexChartAsync() {
            return base.Channel.GetUpcomIndexChartAsync();
        }
    }
}
