// <auto-generated />
namespace VITV_Web.MigrationsStoreInfo
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changeVNDExchangeRate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeVNDExchangeRate));
        
        string IMigrationMetadata.Id
        {
            get { return "201502020307521_changeVNDExchangeRate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
